dependency-dir: ../lib

include_directories:
  - src/

depends:
  - chibios-syscalls
  - cmp
  - cmp_mem_access
  - error
  - crc
  - version

source:
  - src/vl6180x/vl6180x.c

target.arm:
  - src/main.c
  - src/debug.c
  - src/board.c
  - src/vl6180x/vl6180x_chibios.c
  - src/TCS3472.c
  - src/stubs.cpp
  - src/uavcan/node.cpp
  - src/uavcan/DistanceVL6180X_pub.cpp
  - src/bootloader_config.c
  - ../lib/can-bootloader/config.c

tests:
    - tests/test_range_sensor.cpp

templates:
    app_src.mk.jinja: app_src.mk
    CMakeLists.txt.jinja: CMakeLists.txt
